### PR TITLE
Fix: drand: calculation of round from Filecoin epochs

### LINKED ISSUE #2170: Drand rounds are not computed as drand computes them
**Describe the bug**

Lotus doesn't use the same "timestamp-to-round" mapping than drand:
Drand does the following ([code](https://github.com/drand/drand/blob/master/chain/time.go#L25)):
```go
math.Floor((now - genesis) / drandPeriod) + 1 
```
because round 1 happens at genesis time.
Lotus however does the following ([code](https://github.com/filecoin-project/lotus/blob/master/chain/beacon/drand/drand.go#L188)) :
```go
math.Floor((now - genesis) / drandPeriod) 
```
It's a breaking change to move to drand, but it would be the preferred way. 

**Consequences**: the lotus chain uses a round before the one it should use, having an offset of 2 instead of 1 (i.e. normally it looks at a drand round for one epoch before, but it's in fact using the randomness of one more previous drand round).

### PR DESCRIPTION
**Pull request by arajasek**
## Related Issues

Resolves #2170 

## Proposed Changes

This PR was originally opened for the v14 upgrade, but descoped.

## Checklist

Before you mark the PR ready for review, please make sure that:
- [x] All commits have a clear commit message.
- [x] The PR title is in the form of of `<PR type>: <area>: <change being made>`
    - example: ` fix: mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, _deps_
- [x] This PR has tests for new functionality or change in behaviour
- [x] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

### CODE REVIEW

**Comment by arajasek** [comment]
Added test.

File: chain/beacon/drand/drand.go [hunk 1]
```diff
@@ -201,11 +204,32 @@ func (db *DrandBeacon) VerifyEntry(curr types.BeaconEntry, prev types.BeaconEntr
...
+func (db *DrandBeacon) maxBeaconRoundV2(latestTs uint64) uint64 {
+	if latestTs < db.drandGenTime {
+		return 1
+	}
+
+	fromGenesis := latestTs - db.drandGenTime
+	// we take the time from genesis divided by the periods in seconds, that
+	// gives us the number of periods since genesis.  We also add +1 because
+	// round 1 starts at genesis time.
+	return uint64(math.Floor(float64(fromGenesis)/db.interval.Seconds())) + 1
```
Comment (Kubuxu) [inline chain/beacon/drand/drand.go:232]: I feel a bit uneasy using floats for this.
As you only need Floor it should be simple to do using pure ints.

**Comment by Kubuxu** [comment]
Hey, how does it work during the upgrade?
As I recall currently we track the previous randomness beacon and verify the new one based on the previous one. How does this continue to work during the upgrade?

**Comment by Kubuxu** [comment]
Ahh, right in this upgrade we only add on one breacon. Ok, I can see how that can work.

File: chain/beacon/drand/drand.go (hunk 1 above)
Comment (arajasek) [reply chain/beacon/drand/drand.go:232]: I agree, simplifying this.

**Comment by arajasek** [comment]
Yeah, so what should happen is just that the first block after the upgrade kicks in should have 2 beacon entries (exactly as we have after a null tipset).

File: chain/beacon/drand/drand.go [hunk 2]
```diff
@@ -201,11 +203,32 @@ func (db *DrandBeacon) VerifyEntry(curr types.BeaconEntry, prev types.BeaconEntr
...
+}
+
+func (db *DrandBeacon) maxBeaconRoundV1(latestTs uint64) uint64 {
 	dround := (latestTs - db.drandGenTime) / uint64(db.interval.Seconds())
 	return dround
 }
 
+func (db *DrandBeacon) maxBeaconRoundV2(latestTs uint64) uint64 {
+	if latestTs < db.drandGenTime {
+		return 1
```
Comment (Stebalien) [inline chain/beacon/drand/drand.go:224]: not 0?

Comment (Stebalien) [reply chain/beacon/drand/drand.go:224]: When `latestTs == db.drandGenTime`, the round will be 1. I don't know if it matters, but it may make more sense to let the round be 0 before that.

**Review by Stebalien — APPROVED** [review]

File: chain/beacon/drand/drand.go (hunk 2 above)
Comment (arajasek) [reply chain/beacon/drand/drand.go:224]: Not super important for mainnet, but I think your argument makes sense. Changing.

Comment (arajasek) [reply chain/beacon/drand/drand.go:224]: Actually, looking at Drand code, round 0 seems to indicate a special value that says "give me the latest entry".

Comment (arajasek) [reply chain/beacon/drand/drand.go:224]: https://github.com/drand/drand/blob/master/client/http/http.go#L311-L315

Comment (arajasek) [reply chain/beacon/drand/drand.go:224]: Gonna leave as is, for now.
