### PR TITLE
fix flaky TestDealPublisher and re-enable

### LINKED ISSUE #6799: TestDealPublisher is flaky
As seen in https://app.circleci.com/pipelines/github/filecoin-project/lotus/15905/workflows/5d4be844-ce96-4922-ac4c-09503c0d3b3e/jobs/205203

Specifics:
```
=== RUN   TestDealPublisher/ignore_deals_with_cancelled_context
...
    dealpublisher_test.go:239: 
        	Error Trace:	dealpublisher_test.go:239
        	            				dealpublisher_test.go:126
        	Error:      	"[{{QmTLZn8wTHzQ4Vh9vxi68uN4HiR7EB26ro6paNMP8k61GQ %!s(abi.PaddedPieceSize=0) %!s(bool=false) f2nfm7gnbtxhjvq4bvbdnyrypubdq3xtvr2e2rw5q f24j2ie33bbjxd2oqjnf6o5qcllcbwajp7drnrqmy  20 120 0 0 0} {%!s(crypto.SigType=1) signature data}} {{QmQ3aqKBSY5r8k1CZv7FPhcPEjNG47yzSuzKpfUUgJXdB4 %!s(abi.PaddedPieceSize=0) %!s(bool=false) f2nfm7gnbtxhjvq4bvbdnyrypubdq3xtvr2e2rw5q f24j2ie33bbjxd2oqjnf6o5qcllcbwajp7drnrqmy  20 120 0 0 0} {%!s(crypto.SigType=1) signature data}} {{QmSdveHM1ShmHEjrNyLdkY9MYPyEKCgVvWXHvvbXCTP951 %!s(abi.PaddedPieceSize=0) %!s(bool=false) f2nfm7gnbtxhjvq4bvbdnyrypubdq3xtvr2e2rw5q f24j2ie33bbjxd2oqjnf6o5qcllcbwajp7drnrqmy  20 120 0 0 0} {%!s(crypto.SigType=1) signature data}}]" should have 2 item(s), but has 3
        	Test:       	TestDealPublisher/ignore_deals_with_cancelled_context
```

### PR DESCRIPTION
**Pull request by Stebalien**
fixes #6799

(wanted to see if the issues were related to event handling, but they aren't)

### CODE REVIEW

File: markets/storageadapter/dealpublisher.go [hunk 1]
```diff
@@ -203,9 +204,9 @@ func (p *DealPublisher) processNewDeal(pdeal *pendingDeal) {
 	log.Infof("add deal with piece CID %s to publish deals queue - %d deals in queue (max queue size %d)",
 		pdeal.deal.Proposal.PieceCID, len(p.pending), p.maxDealsPerPublishMsg)
 
-	// If the maximum number of deals per message has been reached,
-	// send a publish message
-	if uint64(len(p.pending)) >= p.maxDealsPerPublishMsg {
+	// If the maximum number of deals per message has been reached or we're not batching, send a
+	// publish message
+	if uint64(len(p.pending)) >= p.maxDealsPerPublishMsg || p.publishPeriod == 0 {
```
Comment (Stebalien) [inline markets/storageadapter/dealpublisher.go:209]: not strictly necessary but makes testing a bit easier (I think?)

**Review by dirkmc — APPROVED** [review]
