### PR TITLE
PriceListByVersion

### LINKED ISSUE #6652: PricelistByEpoch Technical Debt
From @Stebalien 
"
PricelistByEpoch has some pretty serious problems and I'm not sure how to cleanly fix them.
- It takes an epoch, not a network version.
- It applies the price-list at the upgrade epoch, instead of after the upgrade epoch. This is off by one.
- The VM calls PricelistByEpoch(currentEpoch)
- Sync/mpool uses the parent tipset's height.
The first step here would be to try to fix the off-by-one and test it around the calico upgrade. If that fails... this is going to be annoying to maintain going forward.
"

Additionally this has made running new auto-gen test-vectors on lotus hard because these assume the latest actors version is valid at height 0 with current price list.  We could remove that assumption during test-vector generation and use the epoch 0 pricelist but this is a step in the wrong direction.

### PR DESCRIPTION
**Pull request by ZenGround0**
Closes #6652

### CODE REVIEW

File: chain/sync.go [hunk 1]
```diff
@@ -1054,14 +1054,15 @@ func (syncer *Syncer) checkBlockMessages(ctx context.Context, b *types.FullBlock
 		return xerrors.Errorf("failed to load base state tree: %w", err)
 	}
 
-	pl := vm.PricelistByEpoch(baseTs.Height())
+	nv := syncer.sm.GetNtwkVersion(ctx, b.Header.Height)
```
Comment (ZenGround0) [inline chain/sync.go:1057]: I'm changing this from the base tipset's version to the block including the message's version which I think is the desired behavior.

**Review by magik6k — APPROVED** [review]
Looks better than what we had, obviously https://github.com/filecoin-project/go-state-types/pull/30 should land first (probably with the bigger version number changes) (also need the api version bump)

File: chain/stmgr/forks.go [hunk 2]
```diff
@@ -292,6 +296,18 @@ func (us UpgradeSchedule) Validate() error {
 	return nil
 }
 
+func (us UpgradeSchedule) GetNtwkVersion(e abi.ChainEpoch) (network.Version, error) {
```
Comment (ZenGround0) [inline chain/stmgr/forks.go:299]: @magik6k I added this so that the mpool could get current network version without having to construct a new stmgr and depend on chainstore.  If you think this redundancy is unacceptable I can try a deeper refactor.

File: api/version.go [hunk 3]
```diff
@@ -54,8 +54,8 @@ func VersionForType(nodeType NodeType) (Version, error) {
 
 // semver versions of the rpc api exposed
 var (
-	FullAPIVersion0 = newVer(1, 3, 0)
-	FullAPIVersion1 = newVer(2, 1, 0)
+	FullAPIVersion0 = newVer(1, 3, 1)
```
Comment (ZenGround0) [inline api/version.go:57]: @Stebalien @magik6k is there anything else needed to finish bumping the api version?

File: chain/sync.go (hunk 1 above)
Comment (ZenGround0) [reply chain/sync.go:1057]: Good call out.  I checked this against mainnet and this code syncs past the calico upgrade (265060 to 265241 so far) so we should be all good.

File: api/version.go (hunk 3 above)
Comment (Kubuxu) [reply api/version.go:57]: I think that is it.

File: chain/stmgr/forks.go (hunk 2 above)
Comment (Kubuxu) [reply chain/stmgr/forks.go:299]: Seems fine with me

**Comment by magik6k** [comment]
(marking as draft until we land https://github.com/filecoin-project/go-state-types/pull/30)
