### PR TITLE
fix: eth: re-execute tipsets on missing events

### LINKED ISSUE #11335: FEVM: Re-execute tipset on missing events
If an Eth JSON-RPC API like `EthGetTransactionReceipt` fails because we're missing the transaction's events (e.g., because we enabled the Ethereum API _after_ we processed the tipset, we should re-execute the tipset.

This will cause some work on otherwise pure "lookup" API requests however, this should only happen _once_ and it should only happen for "old" tipsets. Although we _do_ need to make sure that it only happens once (we may need some way to lock/deduplicate such requests?).

See https://github.com/filecoin-project/lotus/issues/11325.

### PR DESCRIPTION
**Pull request by Stebalien**
## Related Issues

fixes #11335

## Proposed Changes

This will re-execute tipsets to forcibly re-compute and store events when they're missing. This is effectively lazy backfilling of events.

NOTE: This _won't_ backfill the index itself, it'll just give us the events.

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [x] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [x] New features have usage guidelines and / or documentation updates in
  - [x] [Lotus Documentation](https://lotus.filecoin.io)
  - [x] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

File: node/impl/full/eth_utils.go [hunk 1]
```diff
@@ -731,6 +731,24 @@ func newEthTxReceipt(ctx context.Context, tx ethtypes.EthTx, lookup *api.MsgLook
 		receipt.ContractAddress = &addr
 	}
 
+	var events []types.Event
+	if rct := lookup.Receipt; rct.EventsRoot != nil {
+		events, err = ca.ChainGetEvents(ctx, *rct.EventsRoot)
+		if err != nil {
```
Comment (snissn) [inline node/impl/full/eth_utils.go:737]: should we match a specific error here, or is just any error correct enough ?

Comment (Stebalien) [reply node/impl/full/eth_utils.go:737]: Worst case, we'll waste some CPU if the datastore is corrupted. Then we'll return the same error below when we try to fetch the events again. Unfortunately, matching errors is kind of error prone.

**Review by aarshkshah1992 — APPROVED** [review]
lgtm
