### PR TITLE
fixes #6786 segfault

### LINKED ISSUE #6786: Segfault in storage sealing
After certain kinds of failures, my filecoin repository gets corrupt in such a way that I always get a segfault (null pointer dereference) on launch.

The segfault occurs on this line. `lookup` is nil.

https://github.com/filecoin-project/lotus/blob/1c30d07d6862708eac6fe1b30b47da74f39b4a0a/extern/storage-sealing/currentdealinfo.go#L72

### PR DESCRIPTION
**Pull request by xloem**
I don't know the code, but given I needed this to bring my node back up, here's a pull request.

### CODE REVIEW

File: extern/storage-sealing/currentdealinfo.go [hunk 1]
```diff
@@ -69,6 +69,10 @@ func (mgr *CurrentDealInfoManager) dealIDFromPublishDealsMsg(ctx context.Context
 		return dealID, nil, xerrors.Errorf("looking for publish deal message %s: search msg failed: %w", publishCid, err)
 	}
 
+	if lookup == nil {
+		return dealID, nil, xerrors.Errorf("looking for publish deal message %s: lookup nil", publishCid)
```
Comment (Stebalien) [inline extern/storage-sealing/currentdealinfo.go:73]:
```suggestion
		return dealID, nil, xerrors.Errorf("looking for publish deal message %s: not found", publishCid)
```

**Review by Stebalien — APPROVED** [review]
Thanks!

**Comment by xloem** [comment]
Thank for addressing this so thoroughly.
