### PR TITLE
fix SectorState

### LINKED ISSUE #3626: ForceSectorState is not doing sanity check with valid states.
After executing command ```lotus-miner sectors update-state --really-do-it 0 -h```,  the sector is updated to status `-h`
image

[sectorsUpdateCmd](https://github.com/filecoin-project/lotus/blob/2080458f0d1235cc0cc255405c13e3c086de0e3f/cmd/lotus-storage-miner/sectors.go#L423) takes the arg string as it is and passes it to [ForceSectorState](https://github.com/filecoin-project/lotus/blob/master/extern/storage-sealing/fsm.go) and send status as it is

### PR DESCRIPTION
**Pull request by deaswang**
fix #3626 
update SectorState type.

### CODE REVIEW

File: extern/storage-sealing/sector_state.go [hunk 1]
```diff
@@ -1,43 +1,43 @@
 package sealing
 
-type SectorState string
+type SectorState uint8
```
Comment (magik6k) [inline extern/storage-sealing/sector_state.go:3]: Changing this will break everyones miner sector states (this is used in on-disk state). Using strings also makes it much easier to migrate states.

The correct fix for this issue is likely just having a list of valid states, and checking against that list in the update-state command

File: extern/storage-sealing/sector_state.go [hunk 2]
```diff
@@ -2,6 +2,8 @@ package sealing
 
 type SectorState string
 
+var ExistSectorStateList = make(map[SectorState]struct{})
```
Comment (magik6k) [inline extern/storage-sealing/sector_state.go:5]: Initializing the values here instead of in init would be cleaner / safer
```suggestion
var ExistSectorStateList = map[SectorState]struct{}{
	Empty: {},
...
}
```

**Comment by magik6k** [comment]
(also looks like we need `go fmt ./...`)

**Review by magik6k — APPROVED** [review]
Looks good, thanks!
