### PR TITLE
fix issue #127

### LINKED ISSUE #127: Auto-reconnect in JsonRPC client
Currently when the client disconnects the behaviour isn't clearly defined.

When the client loses connection, we should block all calls and try to reconnect in background.

### PR DESCRIPTION
**Pull request by jsign**
Closes #127
This is a continuation of https://github.com/filecoin-project/lotus/pull/1146, since the main idea of the other PR changed.

---

There's a new tag available `retry:"true"`.
e.g" 
```
ChainHead              func(context.Context) (*types.TipSet, error)                `perm:"read" retry:"true"`
```
It works the same if the return value is a chan or not.
The meaning is: the function call will not return with failure on a closed websocket channel. It will keep retrying while the connection is trying to be reestablished.

If the connection is closed before `sendRequest`; saying it differently, the method is called with a closed connection:
- if retry is true, will keep trying until the connection is resumed
- if retry is false, will fail immediately with an `err` of closed connection

If the connection is closed after the request was sent, but before received reply (in-flight):
- if retry is true, will retry until connection is resumed
- if retry is false, will fail immediately with an `err`

---

When a connection is lost:
- all in-flight connections are failed (in case of `retry:"true"` cases, they will continue retrying
- all open chans will be closed, so rpc calls that returns chan will close. (doesn't matter if retry is true or not for them)

---
Tested with `ChainHead` and `ChainNotify` and seems to work correctly.

### CODE REVIEW

File: lib/jsonrpc/client.go [hunk 1]
```diff
@@ -269,6 +281,8 @@ type rpcFunc struct {
 
 	hasCtx int
 	retCh  bool
+
+	retry bool
```
Comment (jsign) [inline lib/jsonrpc/client.go]: We save here if was tagged with retry.

File: lib/jsonrpc/client.go [hunk 2]
```diff
@@ -344,27 +358,38 @@ func (fn *rpcFunc) handleRpcCall(args []reflect.Value) (results []reflect.Value)
...
-		}
 
-		retVal = func() reflect.Value { return val.Elem() }
+			retVal = func() reflect.Value { return val.Elem() }
+		}
+		retry := resp.Error != nil && resp.Error.Code == 0 && fn.retry
+		if !retry {
+			break
+		}
+		time.Sleep(time.Second * 3)
```
Comment (jsign) [inline lib/jsonrpc/client.go]: The `handleRpcCall` will keep making the `sendRequest` loop whenever the received error has `.Code==0` which means the connection is reset. But only if `fn.Retry` which means the methods has the `retry` annotation to `true`.
The `time.Sleep` is just to wait for the connection to be reestablished... could have other solutions but would make things hairier.

File: lib/jsonrpc/options.go [hunk 3]
```diff
@@ -0,0 +1,19 @@
+package jsonrpc
+
+import "time"
+
+type Config struct {
+	ReconnectInterval time.Duration
+}
+
+var defaultConfig = Config{
+	ReconnectInterval: time.Second * 5,
```
Comment (jsign) [inline lib/jsonrpc/options.go]: Arbitrary...

File: lib/jsonrpc/options.go [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+}
+
+type Option func(c *Config)
+
+func WithReconnectInterval(d time.Duration) func(c *Config) {
```
Comment (jsign) [inline lib/jsonrpc/options.go]: If for some reason wants to change.

File: lib/jsonrpc/websocket.go [hunk 5]
```diff
@@ -477,9 +511,22 @@ func (c *wsConn) handleWsConn(ctx context.Context) {
 			c.handleFrame(ctx, frame)
 			go c.nextMessage()
 		case req := <-c.requests:
+			c.writeLk.Lock()
 			if req.req.ID != nil {
+				if c.incomingErr != nil { // No conn?, immediate fail
```
Comment (jsign) [inline lib/jsonrpc/websocket.go]: Interestingly, whenever gorilla detects the connection is closed, it closes `c.incoming`. Didn't expect that but found it while making some tests. So we never assume after reading `<-c.requests` that we have a good conn. `c.incomingErr` is set again to `nil` when conn is reestablished (line 490)

File: lib/jsonrpc/websocket.go [hunk 6]
```diff
@@ -432,34 +461,39 @@ func (c *wsConn) handleWsConn(ctx context.Context) {
...
 		select {
 		case r, ok := <-c.incoming:
 			if !ok {
 				if c.incomingErr != nil {
 					if !websocket.IsCloseError(c.incomingErr, websocket.CloseNormalClosure) {
 						log.Debugw("websocket error", "error", c.incomingErr)
+						// connection dropped unexpectedly, do our best to recover it
+						c.closeInFlight()
+						c.closeChans()
+						c.incoming = make(chan io.Reader) // listen again for responses
```
Comment (magik6k) [inline lib/jsonrpc/websocket.go]: Need to reset `c.handling` and `c.inflight` so they can be GCed (here or in closeInFlight)

File: lib/jsonrpc/websocket.go [hunk 7]
```diff
@@ -419,6 +422,32 @@ func (c *wsConn) handleFrame(ctx context.Context, frame frame) {
 	}
 }
 
+func (c *wsConn) closeInFlight() {
+	for id, req := range c.inflight {
+		req.ready <- clientResponse{
+			Jsonrpc: "2.0",
+			ID:      id,
+			Error: &respError{
+				Message: "handler: websocket connection closed",
```
Comment (magik6k) [inline lib/jsonrpc/websocket.go]: Should probably set a Code that isn't 0, it mildly bugs me.

Comment (jsign) [reply lib/jsonrpc/websocket.go]: Yeah, agree, will choose `2` since would be the next unused value.

**Comment by jsign** [comment]
Points addressed!

File: lib/jsonrpc/client.go [hunk 8]
```diff
@@ -344,27 +358,38 @@ func (fn *rpcFunc) handleRpcCall(args []reflect.Value) (results []reflect.Value)
...
-		}
 
-		retVal = func() reflect.Value { return val.Elem() }
+			retVal = func() reflect.Value { return val.Elem() }
+		}
+		retry := resp.Error != nil && resp.Error.Code == 2 && fn.retry
+		if !retry {
+			break
+		}
+		time.Sleep(time.Second * 3)
```
Comment (Kubuxu) [inline lib/jsonrpc/client.go]: Should be either a defined constant or an option.

Comment (jsign) [reply lib/jsonrpc/client.go]: Done. Preferred a constant since having two knobs, one for wsconnection retry and one for method retry may be too confusing. This `time.Sleep` was to avoid some more complex solution... sounds that if this should be tuned for a good reason, it should be reconsidered being the correct solution.
