### PR TITLE
fix: #7869 sealing: Add more deal expiration checks during PRU pipeline

### LINKED ISSUE #7869: Fail early if the deals are expired during PRU handlings
like in `handleReplicaUpdate`, we should add more deal error/expiration handling in `handleProveReplicaUpdate1` and `handleProveReplicaUpdate2`

### PR DESCRIPTION
**Pull request by jennijuju**
## Related Issues

resolves #7869 

## Proposed Changes

add more deal error handling during PRU pipeline so that we can fail early without  wasting too much work 

## Checklist

Before you mark the PR ready for review, please make sure that:
- [x] All commits have a clear commit message.
- [x] The PR title is in the form of of `<PR type>: <#issue number> <area>: <change being made>`
    - example: ` fix: #1234 mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_, _misc_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_
- [ ] This PR has tests for new functionality or change in behaviour
- [ ] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

### CODE REVIEW

File: extern/storage-sealing/checks.go [hunk 1]
```diff
@@ -80,6 +79,24 @@ func checkPieces(ctx context.Context, maddr address.Address, si SectorInfo, api
 	return nil
 }
 
+func checkDealExpiration(ctx context.Context, sector SectorInfo, api SealingAPI) error {
```
Comment (arajasek) [inline extern/storage-sealing/checks.go:82]: I don't think this is sufficiently different or faster than checkPieces to warrant its own method?

**Review by arajasek — COMMENTED** [review]
1) i don't know how long `ProveReplicaUpdate1` takes, but it may be rerunning the check before calling `ProveReplicaUpdate2`?
2) what we really want is probably to extend `SectorInfo` to have a `deadline` epoch set to its latest deal activation (can be updated along the way as precommit and so on happens). then, every state transition can check if the sector is doomed before investing any more time in it. 

but that is outside the scope of this pr -- an issue would be nice to have, though.

File: extern/storage-sealing/checks.go (hunk 1 above)
Comment (jennijuju) [reply extern/storage-sealing/checks.go]: > 1. i don't know how long `ProveReplicaUpdate1` takes, but it may be rerunning the check before calling `ProveReplicaUpdate2`?

PRU1 computes the vanilia proofs so yah it should take a while, added another check before the PRU2

Comment (jennijuju) [reply extern/storage-sealing/checks.go]: tho i do think it makes sense to check before PRU2 instead of PRU1 - updated

**Comment by jennijuju** [comment]
> 2. what we really want is probably to extend `SectorInfo` to have a `deadline` epoch set to its latest deal activation (can be updated along the way as precommit and so on happens). then, every state transition can check if the sector is doomed before investing any more time in it.

i understand what you are proposing wrt the adding to sector info, but the earliest deal start epoch should stay the same after the snap deal sector is packed, so it wont be updated once set?

**Review by arajasek — APPROVED** [review]
