### PR TITLE
Fix Drand fetching around null tipsets

### LINKED ISSUE #3613: Lotus fetches drand from chain backwards with null blocks while specs fetches forward
**Describe the bug**
There is a diff with the spec as to how fetch drand entry from the chain.
Lotus will look backward in the chain as long as it doesn't find a drand entry inside ([code](https://github.com/filecoin-project/lotus/blob/master/chain/store/store.go#L1254)). Also, given a certain epoch to fetch drand randomness from, Lotus starts from the round _before_  if the height chosen falls on a null block ([code](https://github.com/filecoin-project/lotus/blob/master/chain/store/store.go#L1084)).

The spec starts by deciding the minimum Filecoin block height and then looks forwards if it encounters null blocks ([spec](https://github.com/filecoin-project/specs/pull/967/files#diff-87cc0d9a7d9c4d4e2775cccff7e8623eR93))

**Expected behavior**

In case of null rounds, drand entries will be inserted at later rounds (even adversarially) - so lotus should fetch it from later blocks as well.

**Reasoning**: Using this behavior, a malicious miner can decide to withold its block or not, and that changes the randomness for a given epoch. If he witholds the block at height `e` and he's the only winner, then the randomness associated with height `e` is the one at the block at height `e-1`. If he doesn't, then the randomness is the one associated with this block at height `e`.

### PR DESCRIPTION
**Pull request by arajasek**
Closes #3613

### CODE REVIEW

File: chain/store/rand.go [hunk 1]
```diff
@@ -79,16 +69,27 @@ func (cs *ChainStore) GetBeaconRandomness(ctx context.Context, blks []cid.Cid, p
...
+	if err != nil {
+		return nil, err
+	}
 
-func (cs *ChainStore) GetChainRandomnessLookingForward(ctx context.Context, blks []cid.Cid, pers crypto.DomainSeparationTag, round abi.ChainEpoch, entropy []byte) ([]byte, error) {
-	return cs.GetChainRandomness(ctx, blks, pers, round, entropy, false)
+	be, err := cs.ExtractBeaconEntryForRound(randTs, uint64(round))
+	if err != nil {
+		log.Errorf("failed to get beacon entry as expected: %w", err)
+		// If this failed for some reason, just use the latest entry (lest we halt the chain)
```
Comment (arajasek) [inline chain/store/rand.go:81]: Bad idea? Better to just fail & stop?

File: chain/sync_test.go [hunk 2]
```diff
@@ -1037,81 +1035,6 @@ func TestSyncCheckpointEarlierThanHead(t *testing.T) {
 	require.True(tu.t, p1Head.Equals(b.TipSet()))
 }
 
-func TestDrandNull(t *testing.T) {
```
Comment (arajasek) [inline chain/sync_test.go:1040]: This test was pretty bad...better test in rand_test now that also covers this case

File: chain/store/rand.go (hunk 1 above)
Comment (nikkolasg) [reply chain/store/rand.go:81]: If a node can't retrieve the beacon at this round for network reason, that means he'll try to get the one before, is that right ? In that case, it can cause a split with him and the rest of the chain no ?

Comment (arajasek) [reply chain/store/rand.go:81]: Yes...but if every node runs into the same problem, this would keep the network going (violating the spec in the process)

I'm almost certain we don't wanna do this, but wanted to get feedback

File: chain/store/rand.go [hunk 3]
```diff
@@ -146,6 +143,56 @@ func (cs *ChainStore) GetLatestBeaconEntry(ts *types.TipSet) (*types.BeaconEntry
 	return nil, xerrors.Errorf("found NO beacon entries in the 20 latest tipsets")
 }
 
+func (cs *ChainStore) ExtractBeaconEntryForRound(ts *types.TipSet, round uint64) (*types.BeaconEntry, error) {
+	cbe := ts.Blocks()[0].BeaconEntries
+	for _, v := range cbe {
+		if v.Round == round {
```
Comment (Kubuxu) [inline chain/store/rand.go:149]: You are passing ChainEpoch as round and comparing it with Drand round.

File: chain/store/store.go [hunk 4]
```diff
@@ -1189,3 +1189,38 @@ func breakWeightTie(ts1, ts2 *types.TipSet) bool {
...
 }
+
+func (cs *ChainStore) GetTipSetFromKey(tsk types.TipSetKey) (*types.TipSet, error) {
+	if tsk.IsEmpty() {
+		return cs.GetHeaviestTipSet(), nil
+	}
+	return cs.LoadTipSet(tsk)
+}
+
+func (cs *ChainStore) GetLatestBeaconEntry(ts *types.TipSet) (*types.BeaconEntry, error) {
```
Comment (arajasek) [inline chain/store/store.go:1200]: This could be in the new stateRand instead, doesn't really make a difference

**Review by Kubuxu — APPROVED** [review]

**Review by magik6k — COMMENTED** [review]
Post-merge lgtm

File: chain/store/rand.go (hunk 1 above)
Comment (nicola) [reply chain/store/rand.go]: wait, does this create a world where a block at an epoch could have two different beacons? if yes, then this is a problem.

Comment (nikkolasg) [reply chain/store/rand.go]: Yes the default behaviour should be that we can't validate this block (yet), we can't assume "everyone on the network has the same problem accessing drand".

Comment (arajasek) [reply chain/store/rand.go]: This is outdated, the code has been removed
