### PR TITLE
fix serialization of paych vouchers

### LINKED ISSUE #522: lotus client retrieve error
ylz@ylz-KVM:~$ ./lotus client retrieve bafkreibwnsjtinmfc2vpeod4ayg3aygupqqrglips34mvtmivdertzitku hello.txt
2019-10-31T17:37:25.184+0800	WARN	main	lotus/main.go:70	RetrieveUnixfs: retrieval exchange: setting up retrieval payment: failed to persist voucher: missing an atlas entry describing how to marshal type types.SignedVoucher (and auto-atlasing for structs is not enabled)

### PR DESCRIPTION
**Pull request by whyrusleeping**
Should close #522

### CODE REVIEW

File: paych/store.go [hunk 1]
```diff
@@ -64,12 +59,12 @@ func dskeyForChannel(addr address.Address) datastore.Key {
 func (ps *Store) putChannelInfo(ci *ChannelInfo) error {
 	k := dskeyForChannel(ci.Channel)
 
-	b, err := cbor.DumpObject(ci)
-	if err != nil {
+	buf := new(bytes.Buffer)
+	if err := ci.MarshalCBOR(buf); err != nil {
```
Comment (magik6k) [inline paych/store.go]: cborrpc pkg has a nicer helper which uses cbor-gen

Comment (magik6k) [reply paych/store.go]: (btw, we should probably make it not use ipld-cbor at all)

File: retrieval/miner.go [hunk 2]
```diff
@@ -221,11 +224,12 @@ func (hnd *handlerDeal) accept(deal DealProposal) error {
 			return
 		}*/
 
-		block := Block{
+		block := &Block{
 			Prefix: nd.Cid().Prefix().Bytes(),
 			Data:   nd.RawData(),
 		}
 
+		fmt.Println("retrieval sending block: ", i, blocksToSend, len(nd.RawData()))
```
Comment (magik6k) [inline retrieval/miner.go]: log.Info?

File: retrieval/types.go [hunk 3]
```diff
@@ -26,15 +25,6 @@ const (
 )
 
 func init() {
```
Comment (magik6k) [inline retrieval/types.go]: Why keep empty init?
