### PR TITLE
Aftering importing a previously deleted key, be able to delete it again.

### LINKED ISSUE #4621: Bug: Wallet doesn't let you delete, import, then delete again
**Describe the bug**
I export the private key firstly, then i delete the wallet address, then import the address again, and then, i want to delete the wallet address again. At last i fail to delete the wallet address.

**To Reproduce**
1. Run 'lotus wallet export f1xxxxxxx > f1xxxxxx.keyinfo'
2. Run 'lotus wallet delete f1xxxxxx', this time the address is deleted as expected
3. Run 'lotus wallet import f1xxxxxx.keyinfo'
4. Run 'lotus wallet delete f1xxxxxx'
5. Cannot delete the wallet address any more
root@241:/home/test# lotus wallet delete f1xxxxxx
ERROR: failed to mark key f1xxxxxx as trashed: checking key before put 'trash-f1xxxxxx': key already exists

**Expected behavior**
The wallet address should be deleted as expected.

**Screenshots**
N/A

**Version (run `lotus version`):**
lotus version 1.1.2+git.009f0962

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by jennijuju**
fixes #4621

### CODE REVIEW

File: node/repo/fsrepo.go [hunk 1]
```diff
@@ -486,7 +487,7 @@ func (fsr *fsLockedRepo) Put(name string, info types.KeyInfo) error {
 	keyPath := fsr.join(fsKeystore, encName)
 
 	_, err := os.Stat(keyPath)
-	if err == nil {
+	if err == nil && !strings.HasPrefix(name, wallet.KTrashPrefix) {
```
Comment (arajasek) [inline node/repo/fsrepo.go:490]: This will go on to overwrite the existing trash key file in the case described in #4621, when we could just return at this point. I'd suggest doing: 

```suggestion
	if err == nil && strings.HasPrefix(name, wallet.KTrashPrefix) {
	    // Fine to try to write the same trash-prefixed file multiple times
	    return nil
	} else if err == nil {
	    return xerrors.Errorf("checking key before put '%s': %w", name, types.ErrKeyExists)
	} else if !os.IsNotExist(err) {
		return xerrors.Errorf("checking key before put '%s': %w", name, err)			
	}
```

**Review by arajasek — CHANGES_REQUESTED** [review]
It's probably "correcter", but a bit riskier, to instead catch the problem described in #4621 at the "import" stage, by deleting any trash-prefixed files for the newly imported private key.

It's always scary to be deleting private key files, though, so maybe not?

**Review by arajasek — APPROVED** [review]
Approved, but someone else should weigh in on:

> It's probably "correcter", but a bit riskier, to instead catch the problem described in #4621 at the "import" stage, by deleting any trash-prefixed files for the newly imported private key.
It's always scary to be deleting private key files, though, so maybe not?

File: node/repo/fsrepo.go [hunk 2]
```diff
@@ -486,7 +487,14 @@ func (fsr *fsLockedRepo) Put(name string, info types.KeyInfo) error {
...
-	if err == nil {
+	if err == nil && strings.HasPrefix(name, wallet.KTrashPrefix) {
+	    // Fine to try to write the same trash-prefixed file multiple times
+	    return nil
+	} else if err == nil {
+	    return xerrors.Errorf("checking key before put '%s': %w", name, types.ErrKeyExists)
+	} else if !os.IsNotExist(err) {
+		return xerrors.Errorf("checking key before put '%s': %w", name, err)			
+	}
 		return xerrors.Errorf("checking key before put '%s': %w", name, types.ErrKeyExists)
```
Comment (arajasek) [inline node/repo/fsrepo.go:498]: That...doesn't look right

Comment (arajasek) [inline node/repo/fsrepo.go:498]: That doesn't look right

**Review by arajasek — CHANGES_REQUESTED** [review]

File: node/repo/fsrepo.go (hunk 2 above)
Comment (jennijuju) [reply node/repo/fsrepo.go:498]: git sucks.

**Comment by arajasek** [comment]
Might also fix https://github.com/filecoin-project/lotus/issues/4306?

**Comment by strahe** [comment]
When the key is imported again, perhaps the trash-key should be deleted, which does no harm, but it is also unnecessary.when trash-key and wallet-key exist at the same time, maybe some people don't understand its meaning?

**Review by magik6k — COMMENTED** [review]
Ideally we wouldn't overwrite the old key, even if it's basically guaranteed to be the same data

I'd:
* Change `Put(..)` to `put(name, info, retries)`
* If retries > 0, append -%d to the name we use for checking
* If it's an existing trash key, call `put` with retries+1

**Review by arajasek — APPROVED** [review]
LGTM
