### PR TITLE
Fix VRF chain randomness

### LINKED ISSUE #2778: VRF tickets should be a chain
We are still working on this.

The current ticket does not use the ticket from the previous epoch as input.

This means that the ticket chain is not "specific" to a chain anymore. This has implications on the validity of SealRandomness.

### PR DESCRIPTION
**Pull request by nicola**
This change ensures that the VRF is always a chain.

Previous behavior: previous randomness was only used when there were no drand values.

Current correct behavior: VRF ticket is generated this block's drand value and previous tipset's ticket

Fixes #2778

### CODE REVIEW

File: cmd/lotus/debug_advance.go [hunk 1]
```diff
@@ -46,6 +46,7 @@ func init() {
 					return xerrors.Errorf("StateMinerWorker: %w", err)
 				}
 
+				// XXX: This can't be right
 				rand, err := api.ChainGetRandomnessFromTickets(ctx, head.Key(), crypto.DomainSeparationTag_TicketProduction, head.Height(), addr.Bytes())
```
Comment (nicola) [inline cmd/lotus/debug_advance.go:50]: We need help on this command, what is this trying to achieve?

**Review by nikkolasg — APPROVED** [review]

File: cmd/lotus/debug_advance.go (hunk 1 above)
Comment (whyrusleeping) [reply cmd/lotus/debug_advance.go:50]: filename: `debug_advance.go`

it just makes a block in debug mode. where pretty much all checks are disabled

Comment (nicola) [reply cmd/lotus/debug_advance.go:50]: I am not too sure what randomness need to be retrieved here and not important for my PR(?)

File: chain/gen/gen.go [hunk 2]
```diff
@@ -358,7 +358,9 @@ func (cg *ChainGen) nextBlockProof(ctx context.Context, pts *types.TipSet, m add
 		return nil, nil, nil, xerrors.Errorf("failed to cbor marshal address: %w", err)
 	}
 
-	buf.Write(pts.MinTicket().VRFProof)
+	if round > build.UpgradeSmokeHeight {
```
Comment (nicola) [inline chain/gen/gen.go:361]: what is this?

Comment (Kubuxu) [reply chain/gen/gen.go:361]: It is how you do upgrades.

**Review by Kubuxu — APPROVED** [review]

**Comment by arajasek** [comment]
rebased / fixed conflicts

File: chain/sync.go [hunk 3]
```diff
@@ -891,10 +891,12 @@ func (syncer *Syncer) ValidateBlock(ctx context.Context, b *types.FullBlock) (er
...
 
-		beaconBase := *prevBeacon
-		if len(h.BeaconEntries) == 0 {
+		if h.Height > build.UpgradeSmokeHeight {
 			buf.Write(baseTs.MinTicket().VRFProof)
-		} else {
+		}
+
+		beaconBase := *prevBeacon
+		if len(h.BeaconEntries) != 0 {
```
Comment (Stebalien) [inline chain/sync.go:899]: Q: should this be an error?

File: cmd/lotus/debug_advance.go (hunk 1 above)
Comment (Stebalien) [reply cmd/lotus/debug_advance.go:50]: So, dead code? Because this doesn't generate the correct randomness.

**Review by Stebalien — COMMENTED** [review]
Nothing seems wrong, but I don't know enough to actually approve it.

**Comment by arajasek** [comment]
Running a sync test with this to be safe, good until height 1325 so far

**Review by magik6k — APPROVED** [review]

File: cmd/lotus/debug_advance.go (hunk 1 above)
Comment (whyrusleeping) [reply cmd/lotus/debug_advance.go:50]: it just doesnt matter, its not verified

File: chain/sync.go (hunk 3 above)
Comment (whyrusleeping) [reply chain/sync.go:899]: i don't think so?

**Review by arajasek — APPROVED** [review]

File: cmd/lotus/debug_advance.go (hunk 1 above)
Comment (Kubuxu) [reply cmd/lotus/debug_advance.go:50]: It needs to be anything IIRC.

File: chain/sync.go (hunk 3 above)
Comment (nicola) [reply chain/sync.go:899]: @Stebalien did you resolve this?

Comment (Stebalien) [reply chain/sync.go:899]: No. I'm hardly an expert on how this should work.
