### PR TITLE
fix: itest: fix eth deploy test flake

### LINKED ISSUE #10824: Deflake TestDeployment test
Notes on deflaking captured in code TODOs:

https://github.com/filecoin-project/lotus/blob/554dd2f1eee19ddc0de0aeade7507eec5460d7b2/itests/eth_deploy_test.go#L39

### PR DESCRIPTION
**Pull request by Stebalien**
## Related Issues

fixes #10824

## Proposed Changes

This fixes the TestDeployment flakiness by:

1. Pause mining before submitting the message. That way, we force it to get stuck in the message pool.
2. Removing the logic that asks lotus for the "latest" block. We have other tests that exercise "latest".

### CODE REVIEW

**Comment by Stebalien** [comment]
(validated by reducing the block times back to 100ms and ensuring that the test still passes)

File: itests/eth_deploy_test.go [hunk 1]
```diff
@@ -93,6 +87,15 @@ func TestDeployment(t *testing.T) {
 	pendingFilter, err := client.EthNewPendingTransactionFilter(ctx)
 	require.NoError(t, err)
 
+	// Disconnect peers so we can send messages without propegating them.
```
Comment (arajasek) [inline itests/eth_deploy_test.go:90]: This should work, but is it need easier to just pause and resume mining?

Comment (Stebalien) [reply itests/eth_deploy_test.go:90]: I can do that?

Comment (Stebalien) [reply itests/eth_deploy_test.go:90]: I can do that...

Comment (Stebalien) [reply itests/eth_deploy_test.go]: Done.

**Comment by snissn** [comment]
Looks good to me! Is this error anything to be concerned about? https://app.circleci.com/pipelines/github/filecoin-project/lotus/28594/workflows/c7893a5e-2a10-4e48-a91a-afeb21fdaa23/jobs/962256?invite=true#step-104-510

**Comment by Stebalien** [comment]
Nope, that's intentional:

https://github.com/filecoin-project/lotus/blob/e6c8072f505f724f869861ca0430101fc87286c0/itests/eth_deploy_test.go#L153-L157

(not sure _why_ that's a part of the test, but it is)

File: itests/eth_deploy_test.go [hunk 2]
```diff
@@ -93,6 +88,11 @@ func TestDeployment(t *testing.T) {
 	pendingFilter, err := client.EthNewPendingTransactionFilter(ctx)
 	require.NoError(t, err)
 
+	// Pause so we can test that everything works while the message is in the message pool.
+	for _, miner := range miners {
```
Comment (arajasek) [inline itests/eth_deploy_test.go:92]: Should just be the one miner because `EnsembleMinimal`, but I'm good with this.

**Review by arajasek — APPROVED** [review]
