### PR TITLE
reorder `transfer` checks so as to ensure sending 2B FIL to yourself fails if you don't have that amount

### LINKED ISSUE #7596: Tweak autosend behaviour
We currently short circuit (and always succeed) the balance transfer step if the sender is the same as the receiver. That's fine, but it's slightly nicer to instead fail if the sender doesn't have the appropriate amount of FIL (and do nothing if they do).

### PR DESCRIPTION
**Pull request by laudiacay**
Fixes #7596.

### CODE REVIEW

**Comment by jennijuju** [comment]
is this rebased onto or based off the right branch?

File: chain/vm/vm.go [hunk 1]
```diff
@@ -869,49 +869,86 @@ func (vm *VM) incrementNonce(addr address.Address) error {
...
+		}
 
-	f, err := vm.cstate.GetActor(fromID)
-	if err != nil {
-		return aerrors.Fatalf("transfer failed when retrieving sender actor: %s", err)
+		if fromID == toID {
+			return nil
+		}
+
+		if amt.LessThan(types.NewInt(0)) {
```
Comment (arajasek) [inline chain/vm/vm.go:905]: Since we're changing validation order here, I'd move this up to perhaps the very start of this if-block -- it's pretty much the cheapest thing there is to validate.

File: chain/vm/vm.go [hunk 2]
```diff
@@ -869,49 +869,86 @@ func (vm *VM) incrementNonce(addr address.Address) error {
...
-	}
+		if f.Balance.LessThan(amt) {
+			return aerrors.Newf(exitcode.SysErrInsufficientFunds, "transfer failed, insufficient balance in sender actor: %v", f.Balance)
+		}
 
-	if fromID == toID {
-		return nil
-	}
+		if from == to {
+			return nil
```
Comment (arajasek) [inline chain/vm/vm.go:893]: let's throw in an info log for this case (and the subsequent auto-send cases below)

File: chain/vm/runtime.go [hunk 3]
```diff
@@ -332,7 +332,7 @@ func (rt *Runtime) DeleteActor(beneficiary address.Address) {
 		}
 
 		// Transfer the executing actor's balance to the beneficiary
-		if err := rt.vm.transfer(rt.Receiver(), beneficiary, act.Balance); err != nil {
+		if err := rt.vm.transfer(rt.Receiver(), beneficiary, act.Balance, rt.vm.ntwkVersion(rt.ctx, rt.vm.blockHeight)); err != nil {
```
Comment (arajasek) [inline chain/vm/runtime.go:335]:
```suggestion
		if err := rt.vm.transfer(rt.Receiver(), beneficiary, act.Balance, rt.NetworkVersion()); err != nil {
```

**Review by arajasek — COMMENTED** [review]
Some nits

File: itests/self_sent_txn_test.go [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+	kit.QuietMiningLogs()
+
+	client, _, ens := kit.EnsembleMinimal(t, kit.MockProofs(), kit.GenesisNetworkVersion(network.Version15))
+	ens.InterconnectAll().BeginMining(10 * time.Millisecond)
+
+	bal, err := client.WalletBalance(ctx, client.DefaultKey.Address)
+	require.NoError(t, err)
+
+	// send self half of account balance
+	msgExactlyBal := &types.Message{
```
Comment (arajasek) [inline itests/self_sent_txn_test.go:30]: why is this called exactlybal when it's clearly halfbal

File: itests/self_sent_txn_test.go [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+
+	"github.com/filecoin-project/go-state-types/big"
+	"github.com/filecoin-project/go-state-types/exitcode"
+	"github.com/filecoin-project/lotus/api"
+	"github.com/filecoin-project/lotus/chain/types"
+	"github.com/filecoin-project/lotus/itests/kit"
+	"github.com/stretchr/testify/require"
+)
+
+func TestSelfSentTxn(t *testing.T) {
```
Comment (arajasek) [inline itests/self_sent_txn_test.go:18]: For completeness, it'd be nice to add the exact same test for v14, and assert that both messages succeed there.

File: itests/self_sent_txn_test.go (hunk 4 above)
Comment (laudiacay) [reply itests/self_sent_txn_test.go:30]: im dum

**Review by arajasek — APPROVED** [review]

File: itests/self_sent_txn_test.go [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+
+	"github.com/filecoin-project/go-state-types/big"
+	"github.com/filecoin-project/go-state-types/exitcode"
+	"github.com/filecoin-project/lotus/api"
+	"github.com/filecoin-project/lotus/chain/types"
+	"github.com/filecoin-project/lotus/itests/kit"
+	"github.com/stretchr/testify/require"
+)
+
+func TestSelfSentTxnV15(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (laudiacay) [reply itests/self_sent_txn_test.go:22]: done
