### PR TITLE
fix(splitstore): fix a panic on revert-only head changes

### LINKED ISSUE #6125: lotus chain sethead --epoch ---> panic: runtime error: index out of range [-1]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

**Describe the bug**
(If you are not sure what the bug is, try to figure it out via a [discussion](https://github.com/filecoin-project/lotus/discussions/new) first!

**Version (run `lotus version`):**
1.8.0
**To Reproduce**
1. Run ' lotus chain sethead --epoch 710309'

2. See error
**lotus daemon  Process crash**

**Expected behavior**

**Logs**
Provide daemon/miner/worker logs, and goroutines(if available) for troubleshooting.
 panic: runtime error: index out of range [-1]

goroutine 842 [running]:
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).HeadChange(0xc001b03600, 0xc07b912030, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/workspace/diancun/lotus/blockstore/splitstore/splitstore.go:410 +0x1ac
github.com/filecoin-project/lotus/chain/store.(*ChainStore).reorgWorker.func1(0xc0001702d0, 0xc00105b800, 0xc068c0c780, 0x33f02c0, 0xc067e2fe40)
        /root/workspace/diancun/lotus/chain/store/store.go:525 +0x695
created by github.com/filecoin-project/lotus/chain/store.(*ChainStore).reorgWorker
        /root/workspace/diancun/lotus/chain/store/store.go:490 +0x118

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Stebalien**
Calling, e.g., `lotus chain sethead` on an ancestor tipset won't apply any new blocks, it'll just revert a bunch. This will lead to HeadChange calls with no new blocks to apply.

fixes #6125

### CODE REVIEW

File: blockstore/splitstore/splitstore_test.go [hunk 1]
```diff
@@ -169,6 +169,9 @@ func testSplitStore(t *testing.T, cfg *Config) {
 			t.Errorf("expected %d hot blocks, but got %d", 7, hotCnt)
 		}
 	}
+
+	// Make sure we can revert without panicing.
```
Comment (arajasek) [inline blockstore/splitstore/splitstore_test.go:173]:
```suggestion
	// Make sure we can revert without panicking.
```

**Review by arajasek — APPROVED** [review]
